### ISSUE TITLE
FirmaDostawcza

### ISSUE THREAD

**Issue by Merkirus** [farqlia/sklepy_#3]
Zastanawia mi funkcjonalność klasy FirmaDostawcza. W swoich metodach nie dodaje produktów na stan magazynu, a tylko wyświetla komunikat. Czy mógłbym spróbować zrobić jakąś strategię dostaw implementującą analizę albo cokolwiek, aby klasa miała realny wpływ?

**Comment by farqlia** [comment]
Tak, to bardzo dobry pomysł, możesz zmodyfikować tą klasę wedle swojego pomysłu, czy też dodać nowe jeśli będą potrzebne. Od siebie dodam, że ciekawie by było gdyby w jakiś sposób była zwracana przewidywana data dostawy produktu: np. gdy klient chce kupić jakiś produkt, a nie ma go na magazynie (w nasze HashMapie jest, ale ma przypisaną wartość 0), to jesteśmy w stanie go poinformować, kiedy produkt może być dostępny.
